using ECommerceBackend.Domain.Addresses;

namespace ECommerceBackend.Application.Contracts.Addresses;
public static class AddressMappings
{
    public static AddressDto ToAddressDto(this Address address)
    {
        return new AddressDto
        {
            Id = address.Id,
            UserId = address.UserId,
            Name = address.Name,
            Phone = address.Phone,
            Province = address.Province,
            District = address.District,
            Ward = address.Ward,
            AddressLine = address.AddressLine,
            IsDefault = address.IsDefault,
            IsPickUpAddress = address.IsPickUpAddress,
            IsReturnAddress = address.IsReturnAddress
        };
    }

    /// HDHiep - 10/01/2025
    /// <summary>
    /// Convert AddressDto to Address entity
    /// </summary>
    /// <param name="addressDto"></param>
    /// <returns></returns>
    /// <remarks>
    /// Note: This method does not set the Id property of the Address entity. The Id will be generated by the database when the entity is saved.
    /// </remarks>
    public static Address ToAddressEntity(this AddressDto addressDto)
    {
        return Address.Create(
            addressDto.UserId,
            addressDto.Name,
            addressDto.Phone,
            addressDto.Province,
            addressDto.District,
            addressDto.Ward,
            addressDto.AddressLine,
            addressDto.IsDefault,
            addressDto.IsPickUpAddress,
            addressDto.IsReturnAddress
        );
    }
}
